### ISSUE TITLE
[BUG] | Invaders infamy/opinion exploit

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#224]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Playing as Scourge/Legion/Black Empire, player can reset his threat by granting independence to vassals. But former vassals, because of the decision to join invader, will again become player vassals.
And it also gives a huge bonus to the opinion.

**Steps to reproduce the issue:**
Grant independence to vassal

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/53860905-84da1b80-3ff3-11e9-8b5d-51f0c0cc2ef7.png)
![ck2_10](https://user-images.githubusercontent.com/46576860/53861009-e39f9500-3ff3-11e9-8efe-f4c4d19eff96.png)

</details>

**Comment by zumbak04** [comment]
Fixed? This exploit is very difficult to fix since "Grant Independence" is hardcoded. So, I see two solutions:

- Remove these "Join the Scourge/Legion/Black Empire" decisions. This's the worst way... I think.
- Forbid character to join for X years if it was given independence.

It seems to me that the second way is better and... 100 years is pretty fair. If you're player, you still can use "Swear Fealty" to join the Scourge/Legion/Black Empire.
