### ISSUE TITLE
[LOCALIZATION] | Misleading localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#547]
**Mod Version**
0030ea36

**Please explain your issue in as much detail as possible:**
Lvl1 mages can have 1 max mana.
Loc says they can have 5 max mana.

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61981268-d4040580-b001-11e9-89db-28130be29b98.png)

</details>

**Comment by arithon** [comment]
I thought this addition to the localisation useful, because otherwise without knowing the code/localisation files no one ingame knows, if you could get more than 5 mana and should keep saving up or use it for spells... Since I didn't know (from code) how much mana each level of mage and so on can hold, I simply added /5 to the mana-localisation lines.

**Comment by zumbak04** [comment]
Tried to use dynamic localization here, but looks like it's impossible, so I reverted localization. Fixed!
