### ISSUE TITLE
[SUGGESTION] | Longer lasting long lived races

### ISSUE THREAD

**Issue by IXISparky** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#693]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
at the current moment, longer lived races such as elves have a nasty habit of just dying from stress or minor disease despite having a health buff, its a bit silly and unimmersive that peoples known for living long simply perish from a flu or high blood pressure

**Comment by zumbak04** [comment]
I wouldn't call the elves healty.
Looks like magic made natural elven immunity pretty weak.

Night elves:
> With Nordrassil's destruction, so went the night elves' sole source of protection from aging, disease, and frailty.

> Jarod's wife, also from the same era, passed away due to illness tied to aging.

High elves:

> According to the top priests and medics on Azeroth, the only high elves who perished due to the Sunwell's loss were the very old, the very young, and elves who were already in poor health.

But anyway, it was a bug fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/653/commits/a7e867b78f44f07dfdf829c719f50cd300c2e35c , so I'm closing the issue.
