### ISSUE TITLE
"Destruction of Draenor" event text

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#719]
**Mod Version**
e41a90d

**Please explain your issue in as much detail as possible:**

Event text is too long and overlaps with frame, it's not aesthetically pleasing.

<details>

![Безымянный8](https://user-images.githubusercontent.com/46576860/64972767-83e34a00-d8b2-11e9-9f66-cfa0ba9b2b2a.png)

</details>

> Unlikely that the Azeroth's inhabitants will know what happened today

Yeah, unless this event tells everyone about it.

> they will definitely remember that you and the Valiance Expedition

But my char did nothing in Draenor expedition

> Valiance Expedition

Are you sure it's appropriate name for the Horde expedition in Draenor?

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/64972655-51395180-d8b2-11e9-84e1-ccdddaa93820.png)

</details>

[Volcanoth's_Isle594_12_25.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3617605/Volcanoth.s_Isle594_12_25.zip)

**Comment by DJScias** [comment]
I plan to take a look at this, unless someone already has, but sorta want to get a lore refresh together with you for a draft.

I think the second and third paragraph should be rewritten just to be sure.

* **Azeroth's inhabitants knowing what happened:** I feel like this can probably be shifted to the fact that at least the Eastern Kingdoms can "rest easy" now or something. I doubt Kalimdor knows about this, as at this point it was "uncharted' territory (Horde doesn't go there before Thrall either so) so all of Azeroth's inhabitants seems a bit.. Overbearing?
* **Definitely remember:** I don't know if we as players in CK2 have a hand in closing the portal. I've yet to read the specific information in the code in regards to that.. But I feel like, for it to work for everyone (as it's a major pop up).. It should probably be written in a style of: `This victory, and the ones who secured it, will definitely not be forgotten`. This makes the phrase work whether or not you, as the player, had a part in the whole debacle..
* **Valiance Expedition:** To my knowledge the expedition that goes there is called the `Alliance Expedition` or `Alliance Expeditionary Force`. Who rename themselves the `Sons of Lothar` during TBC when you read the memorial stone.. Which means we should probably use one of the two first names instead of the last one that we wouldn't know yet. However if you're not part of the Alliance, or living too far up North, you wouldn't really know all this info either.. So unless we go with the idea of "This information was given widespread" we should probably avoid giving them a full-blown name or the like.

So, what do you think about these suggestions? To me with the ideas and possible rewrite ideas from above this text box could be a lot better.

**Comment by MemeWizard** [comment]
I just remembered another problem that I forgot to report:
You get this text even if you didn't send any expeditionary forces to Draenor.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65496489-3de54200-dec1-11e9-9dec-edcf1e48b951.png)
![image](https://user-images.githubusercontent.com/46576860/65496525-4ccbf480-dec1-11e9-88d2-f0fa387cf6fc.png)

</details>

**Comment by DJScias** [comment]
Hello there,

Just checked the code and it seems there's only two events associated with this and one is from the "Other races" PoV and the other is from the "Horde in Azeroth" PoV.

They both refer, wrongly, to the Valiance expedition.. So I feel like either the fact there is a choice for you not to send one was missed.. Or it's implied, which is possible, that someone always sends an expedition force but that in this case it isn't necessarily yours. This is probably something that can be fixed by my earlier comment by stating `The expedition, with all their help, became the ...` by leaving it intentionally "all-inclusive".

Not sure what your take is on that, feel free to suggest if you think there should be 4 outcomes instead of 2.. Or just change it to be "all-inclusive" so we can keep 2.

**Comment by zumbak04** [comment]
To be honest, I would rewrite this text without mention the expedition. Only Ner'zhul, the Dark Portal and Draenor. The Horde (`EVTDESC_WCBDP_150_case_01`) and the "Alliance (`EVTDESC_WCBDP_150_case_02`) isn't needed since it's neutral notification.

**Comment by DJScias** [comment]
Hrrrh, that makes sense.

Do you want to tackle this @zumbak04 or shall I give it a go and push a possible draft here of the text?

**Comment by zumbak04** [comment]
> Do you want to tackle this @zumbak04 or shall I give it a go and push a possible draft here of the text?

Up to you. I'll be back at fixing bugs when I'm done with other PRs.

**Comment by DJScias** [comment]
Hello there,

I have a first draft that might work, but who knows.

Previously we had `EVTDESC_WCBDP_150_case_01`:
```
The destruction of the Dark Portal as well as the dark magic of the Shadowmoon clan have done their dark deeds. The homeworld of the orcs is dying. There are earthquakes everywhere, the waters of the world go into the abyss and the fel streams burns out fertile meadows. This world is coming to end and there's no salvation. It will be hard for the Horde to find out what exactly happened on Draenor on this day, but every honourable orc will remember the Valiance Expedition and its heroic deeds in suppressing the largest and most dangerous invasion in the history of the new orcish empire. The expedition still can be saved by escaping through one of the portals created by Ner'zhul, but it's hard to say where exactly they lead. It seems that the former shaman himself did the same thing, saving himself and his clan in the Twisting Nether.
```

`EVTDESC_WCBDP_150_case_02`:
```
The destruction of the Dark Portal, as well as the dark magic of the Shadowmoon clan have done it's dark work! Draenor, the world of the orcs, dies! There are earthquakes everywhere, the waters go into the abyss and the streams of fel burn out once fertile meadows. This world is about to end, but there is no path to salvation.\nUnlikely that the Azeroth's inhabitants will know what happened today among the plains of this wild planet, but they will definitely remember that you and the Valiance Expedition became the guarantor of the final victory over the dark forces that were hiding on the other side of the portal.\nThe expedition can still be saved by escaping through one of the portals created by Ner'zhul, but it is difficult to say exactly where those brave adventurers will be lead. It seems that the former shaman himself did just that, saving himself and his clan in the Twisting Nether.
```

And this is the draft for `EVTDESC_WCBDP_150` I got that's a bit changed and more "neutral" in who can receive it:
```
The destruction of the Dark Portal as well as the dark magic of the Shadowmoon clan have done their dark deeds. Draenor, the world of the orcs, dies. There are earthquakes everywhere, the waters fall into the abyss and the streams of fel burn out what was once fertile meadows. This world is about to end and there is no path to salvation.\nIt is unlikely that Azeroth's inhabitants will ever truely know what happened today among the plains of this wild planet, but they will definitely remember the final victory over the invading forces that were hiding on the other side of the portal.\nThere are reports, however, that Ner'zhul, the former shaman, and his clan saved themselves in the Twisting Nether by escaping through one of the portals he created himself.
```

I haven't changed the option reaction to it under `EVTOPTA_WCBDP_150` ("It's horrible!") since that's probably a decent response to a world getting well.. Torn asunder.

This leads to the following:
![image](https://user-images.githubusercontent.com/439655/65602623-77db4480-dfa4-11e9-9648-664d8785724f.png)

Any thoughts or criticism? I tried to include Draenor's info, the Dark Portal info and Ner'zhul's portal stuff in there.

As an aside.. If that is decent, I'll need someone to translate it into German as while I can write in German I doubt I can make it grammatically sound.

**Comment by zumbak04** [comment]
Looks legit, waiting for PR.
