### ISSUE TITLE
Laughing skull spawn location

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#824]
**Mod Version**
fa6d1396

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Laughing skull spawn in your capital, not in dark portal province

**Steps to reproduce the issue:**
Spawn laughing skull clan

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66403938-26917300-e9f0-11e9-85de-4bf8cd55809e.png)

</details>

**Comment by DJScias** [comment]
This seems to be happening due to the fact on this event's firing it'll go to the raiding adventurers events `events\hl_raiding_adventurers_events.txt` specifically `HL.100`, which saves the "capital" of the ROOT (the person who gets it) as `target_province`.. Which is then used as the province and home for that unit to spawn.

I'm not sure if this should be modified directly, as that'd affect every raiding party that triggers that and I'm doubtful all raiding parties have to spawn at the Dark Portal.. So perhaps an exception needs to be made for the laughing skull? I don't know, maybe @zumbak04 has more thoughts on this.

**Comment by zumbak04** [comment]
> I'm not sure if this should be modified directly, as that'd affect every raiding party that triggers that and I'm doubtful all raiding parties have to spawn at the Dark Portal.. So perhaps an exception needs to be made for the laughing skull? I don't know, maybe @zumbak04 has more thoughts on this.

There's way to spawn only the Laughting Skull in the Dark Portral: save the Dark Portal in `target_province` after the clan spawn and modify `HL.100`, so it is not going to save `capital_scopre` in the event target if there's something inside (the Dark Portal).

**Comment by zumbak04** [comment]
Fixed!
