### ISSUE TITLE
Change army location in provinces

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#867]
**Describe your suggestion in full detail below:**

Some positions are really weird if unit moves

Unu'pe
Southpoint
Darkmist
Shadowhoof
Shady Rest
Lost Point
Wyrmbog

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67405751-dbfe2200-f5bd-11e9-808f-788161ab7aae.png)
![image](https://user-images.githubusercontent.com/46576860/67405775-e28c9980-f5bd-11e9-995e-49137117f44a.png)
![image](https://user-images.githubusercontent.com/46576860/67405794-e9b3a780-f5bd-11e9-9b70-d413adf20949.png)
![image](https://user-images.githubusercontent.com/46576860/67405817-f20be280-f5bd-11e9-8500-03e76057649b.png)
![image](https://user-images.githubusercontent.com/46576860/67405841-f89a5a00-f5bd-11e9-93eb-e4a5ac279ee6.png)
![image](https://user-images.githubusercontent.com/46576860/67405861-ff28d180-f5bd-11e9-8e9f-57c15927b43d.png)
![image](https://user-images.githubusercontent.com/46576860/67405897-09e36680-f5be-11e9-9206-91117d677de1.png)

</details>

**Comment by DJScias** [comment]
Figured I'd take a stab at this since I wanted to do something else than programming for once, and I finally learnt to work with the `Nudge` tool.

Please let me know if these positions are good/bad, if so I can still change em.

If they're fine, I'll push this into a PR. :)

<details>
  <summary>Unu'pe</summary>

  **Normal** (I know it's edge of water, but otherwise the moving one will overlap with Barun)

![image](https://user-images.githubusercontent.com/439655/67438534-184c7500-f5f4-11e9-9467-999cd47b7fa6.png)

**Moving**

![image](https://user-images.githubusercontent.com/439655/67438541-1bdffc00-f5f4-11e9-8912-15cb7002d266.png)
</details>

<details>
  <summary>Southpoint</summary>

![image](https://user-images.githubusercontent.com/439655/67438638-5ba6e380-f5f4-11e9-90a1-d0142cfc87fb.png)
</details>

<details>
  <summary>Darkmist</summary>

![image](https://user-images.githubusercontent.com/439655/67438666-682b3c00-f5f4-11e9-9e4e-9185c649873d.png)
</details>

<details>
  <summary>Shadowhoof</summary>

![image](https://user-images.githubusercontent.com/439655/67438672-6bbec300-f5f4-11e9-84b0-4a40f1be7778.png)
</details>

<details>
  <summary>Shady Rest</summary>

![image](https://user-images.githubusercontent.com/439655/67438697-76795800-f5f4-11e9-83ca-5cbeae8df0b8.png)
</details>

<details>
  <summary>Lost Point</summary>

![image](https://user-images.githubusercontent.com/439655/67438701-7aa57580-f5f4-11e9-9552-e40a835ba315.png)
</details>

<details>
  <summary>Wyrmbog</summary>

![image](https://user-images.githubusercontent.com/439655/67438712-82fdb080-f5f4-11e9-9172-4cf4e724b13f.png)

**I fixed both the unit and councilors positions** (below is an img of how they USED to stand)

![image](https://user-images.githubusercontent.com/439655/67438739-96a91700-f5f4-11e9-9c18-2fc8dbc83f60.png)
</details>

**Comment by zumbak04** [comment]
> Figured I'd take a stab at this since I wanted to do something else than programming for once, and I finally learnt to work with the `Nudge` tool.
> 
> Please let me know if these positions are good/bad, if so I can still change em.
> 
> If they're fine, I'll push this into a PR. :)

Unu'pe position is weird, but I think it's just impossible to do it right, so fine.

**Comment by DJScias** [comment]
> > Figured I'd take a stab at this since I wanted to do something else than programming for once, and I finally learnt to work with the `Nudge` tool.
> > Please let me know if these positions are good/bad, if so I can still change em.
> > If they're fine, I'll push this into a PR. :)
> 
> Unu'pe position is weird, but I think it's just impossible to do it right, so fine.

I agree with you, I'm not happy with it either.. But it is indeed impossible due to the size.

Regardless, I'll open the PR when I'm home from work as that's where my updated `Positions.txt` file is.
